language: node_js
cache:
  directories:
    - node_modules
notifications:
  slack: dadi:pnhiL60xOrm7GOglHUmb7xHK
  email: false
node_js:
  - '8'
  - '7'
  - '6'
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@latest; fi
before_script:
  - npm prune